import { z } from "zod/v4";
import type { TeditMcpTool } from "../../mcp-tools.js";

// ponytail: explicit any avoids runtime imports from the source module; tighten when dependency typing matters.
export function makeDISCOVERY_TOOLS(deps: any): readonly TeditMcpTool[] {
  const { detailFlagSchema, fileSchema, runActionsTool, runHistoryTraceTool, runInspectRangeTool, runReadDetailTool, runScanStringsTool, runSearchTextTool, runSearchTool, runSelectTool, runTemplatesTool } = deps;
  return [
    {
      name: "actions",
      title: "Actions",
      description: "List tedit tools/actions plus agent guidance for choosing between native read/edit/write/patch and tedit.",
      category: "discover",
      aliases: ["capabilities", "tool_guide"],
      bestFor: ["tool discovery", "choosing an edit strategy", "checking file-specific rule support"],
      inputSchema: {
        file: z.string().optional(),
        ...detailFlagSchema,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
      handler: runActionsTool,
    },
    {
      name: "templates",
      title: "Templates",
      description: "Read-only list of built-in, global, and project-local .tedit/templates available for file_write mode=template.",
      category: "discover",
      aliases: ["template_list", "list_templates"],
      bestFor: ["discovering scaffold templates", "checking project conventions before file generation", "choosing file_write mode=template"],
      inputSchema: {
        cwd: z.string().optional().describe("Project directory used to resolve .tedit/templates. Defaults to process cwd."),
        ...detailFlagSchema,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
      handler: runTemplatesTool,
    },
    {
      name: "search",
      title: "Search",
      description: "Read-only text/range discovery facade. Pass query for grep-style search, or file plus lines/head/tail for sed/head/tail-style inspection.",
      category: "discover",
      aliases: ["grep", "inspect", "range_context", "text_search"],
      bestFor: ["text discovery", "line context", "grep/sed/head/tail workflows before editing"],
      inputSchema: {
        query: z.string().min(1).optional().describe("Literal search text or regex pattern when regex=true. Omit when inspecting file lines/head/tail."),
        file: fileSchema.optional().describe("File to inspect when using lines/head/tail. Also accepted as single-file search path when query is present."),
        lines: z.string().min(1).optional().describe("Line range such as 42 or 40:50. Mutually exclusive with query/head/tail."),
        head: z.number().int().positive().optional().describe("Inspect the first N lines. Mutually exclusive with query/lines/tail."),
        tail: z.number().int().positive().optional().describe("Inspect the last N content lines. Mutually exclusive with query/lines/head."),
        paths: z.array(z.string().min(1)).optional().describe("Files or directories to search. Defaults to cwd."),
        path: z.string().min(1).optional().describe("Single file or directory alias for paths."),
        regex: z.boolean().optional().describe("Treat query as a JavaScript regular expression."),
        glob: z.string().optional().describe("Simple glob filter, e.g. **/*.tsx."),
        context: z.number().int().nonnegative().optional().describe("Additional lines before and after each result or requested range."),
        multieditSpec: z.boolean().optional().describe("Also return a file-grouped multiedit spec for replacing the matched query."),
        replace: z.string().optional().describe("Replacement text for multieditSpec. Defaults to a placeholder."),
        maxResults: z.number().int().positive().optional().describe("Maximum result count. Defaults to 100."),
        caseSensitive: z.boolean().optional().describe("Use case-sensitive matching. Literal and regex searches default to case-insensitive."),
        includeHidden: z.boolean().optional().describe("Include hidden files and directories except built-in excluded directories."),
        output: z.enum(["compact", "detailed"]).optional().describe("Response shape. Defaults to compact; detailed includes full per-result context and suggestions."),
        includeDetails: z.boolean().optional().describe("Return the detailed response shape."),
        ...detailFlagSchema,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
      handler: runSearchTool,
    },
    {
      name: "inspect_range",
      title: "Inspect Range",
      description: "Read-only line/context inspection for sed/head/tail-style workflows. Returns line objects, byte range, parse status, and edit-ready suggestions.",
      category: "discover",
      aliases: ["inspect-range", "range_context", "sed_range"],
      bestFor: ["viewing line context", "turning a line range into edit findLines", "checking parser status around a target"],
      inputSchema: {
        file: fileSchema,
        lines: z.string().min(1).optional().describe("Line range such as 42 or 40:50. Mutually exclusive with head/tail."),
        head: z.number().int().positive().optional().describe("Inspect the first N lines. Mutually exclusive with lines/tail."),
        tail: z.number().int().positive().optional().describe("Inspect the last N content lines. Mutually exclusive with lines/head."),
        context: z.number().int().nonnegative().optional().describe("Additional lines before and after the requested range."),
        ...detailFlagSchema,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
      handler: runInspectRangeTool,
    },
    {
      name: "search_text",
      title: "Search Text",
      description: "Read-only text search bridge for rg/grep workflows. Returns structured candidates with line/byte ranges and inspect/edit follow-ups.",
      category: "discover",
      aliases: ["search-text", "grep_text", "text_search"],
      bestFor: ["raw text discovery", "grep then edit workflows", "finding literal or regex matches across files"],
      inputSchema: {
        query: z.string().min(1).describe("Literal search text or regex pattern when regex=true."),
        paths: z.array(z.string().min(1)).optional().describe("Files or directories to search. Defaults to cwd."),
        path: z.string().min(1).optional().describe("Single file or directory alias for paths."),
        regex: z.boolean().optional().describe("Treat query as a JavaScript regular expression."),
        glob: z.string().optional().describe("Simple glob filter, e.g. **/*.tsx."),
        context: z.number().int().nonnegative().optional().describe("Additional context lines before and after each result."),
        multieditSpec: z.boolean().optional().describe("Also return a file-grouped multiedit spec for replacing the matched query."),
        replace: z.string().optional().describe("Replacement text for multieditSpec. Defaults to a placeholder."),
        maxResults: z.number().int().positive().optional().describe("Maximum result count. Defaults to 100."),
        caseSensitive: z.boolean().optional().describe("Use case-sensitive matching. Literal and regex searches default to case-insensitive."),
        includeHidden: z.boolean().optional().describe("Include hidden files and directories except built-in excluded directories."),
        output: z.enum(["compact", "detailed"]).optional().describe("Response shape. Defaults to compact; detailed includes full per-result context and suggestions."),
        includeDetails: z.boolean().optional().describe("Return the detailed response shape."),
        ...detailFlagSchema,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
      handler: runSearchTextTool,
    },
    {
      name: "read_detail",
      title: "Read Detail",
      description: "Read one large compact-output detail artifact on demand. Supports JSON path, array offset/limit paging, grep, line slicing, and byte limits.",
      category: "discover",
      aliases: ["read-detail", "show_detail", "detail"],
      bestFor: ["reading large compact response fields on demand", "grep/slice artifact data", "avoiding huge MCP responses"],
      inputSchema: {
        id: z.string().optional().describe("Detail id returned in a $detail descriptor."),
        file: z.string().optional().describe("Artifact path returned in a $detail descriptor."),
        path: z.string().optional().describe("Dot-separated JSON path inside the stored value, e.g. 0.value or symbols.0.name."),
        offset: z.number().int().nonnegative().optional().describe("Array item offset after path selection. Use readNext.offset from a $detail descriptor to continue."),
        limit: z.number().int().positive().optional().describe("Maximum array item count after path selection. Separate from limitBytes."),
        grep: z.string().optional().describe("Return only lines containing this string after JSON rendering."),
        lines: z.string().optional().describe("Line slice N or N:M after JSON rendering."),
        limitBytes: z.number().int().positive().optional().describe("Maximum response bytes. Defaults to 8000."),
        detailArtifactDir: z.string().min(1).optional().describe("Artifact directory used with id lookup. Defaults to .tedit-cache/details."),
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
      handler: runReadDetailTool,
    },
    {
      name: "history_trace",
      title: "History Trace",
      description: "Read-only git history trace. Uses blame/log -L for line ranges and log -S/-G for text or regex history.",
      category: "discover",
      aliases: ["history-trace", "git_history", "trace_history"],
      bestFor: ["checking when code changed", "understanding why a line exists before editing", "finding commits that introduced text"],
      inputSchema: {
        file: fileSchema,
        lines: z.string().optional().describe("Line range such as 42 or 40:50. Uses git blame and git log -L."),
        contains: z.string().optional().describe("Literal text to trace with git log -S."),
        regex: z.string().optional().describe("Regex to trace with git log -G."),
        limit: z.number().int().positive().optional().describe("Maximum commits to return. Defaults to 10."),
        ...detailFlagSchema,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
      handler: runHistoryTraceTool,
    },
    {
      name: "scan_strings",
      title: "Scan Strings",
      description: "Read-only JS/TS/JSX AST string scanner for hardcoded user-facing text. Covers JSX text/attrs, string literals, object values, and simple template literals while excluding obvious technical strings by default.",
      category: "ast",
      aliases: ["scan-strings", "hardcoded_text", "i18n_scan"],
      bestFor: ["hardcoded text inventory", "i18n preparation", "finding JS/TS strings beyond JSX selectors"],
      inputSchema: {
        file: fileSchema,
        contains: z.string().optional().describe("Only return strings containing this text."),
        includeExcluded: z.boolean().optional().describe("Include technical strings that are normally excluded, with excludeReason."),
        minLength: z.number().int().positive().optional().describe("Minimum string length. Defaults to 1."),
        ...detailFlagSchema,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
      handler: runScanStringsTool,
    },
    {
      name: "select",
      title: "Universal Select",
      description: "Read-only facade that routes selection by file type: TS/JS declarations, JSX/TSX elements, or text fallback with one common response shape.",
      category: "discover",
      aliases: ["smart_select", "find_symbol", "select_node"],
      bestFor: ["one entrypoint before edit", "TS/JS/JSX/TSX target discovery", "choosing the safest follow-up edit route"],
      inputSchema: {
        file: fileSchema,
        selector: z.string().min(1).optional().describe("Common selector/name/query. Examples: LoginButton, fn:start, class:Server, button.primary, 삭제."),
        name: z.string().min(1).optional().describe("Alias for selector when selecting a named declaration or JSX element."),
        contains: z.string().min(1).optional().describe("Text fallback query or secondary filter for previews."),
        kind: z.enum(["auto", "function", "class", "method", "prop", "var", "import", "jsx", "text"]).optional().describe("Optional route hint. Defaults to auto."),
        context: z.number().int().nonnegative().optional().describe("Context lines for text fallback."),
        maxResults: z.number().int().positive().optional().describe("Maximum normalized matches to return."),
        ...detailFlagSchema,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
      handler: runSelectTool,
    }
  ] satisfies readonly TeditMcpTool[];
}
