import { z } from "zod/v4";
import type { TeditMcpTool } from "../../mcp-tools.js";

// ponytail: explicit any avoids runtime imports from the source module; tighten when dependency typing matters.
export function makeEDIT_TOOLS(deps: any): readonly TeditMcpTool[] {
  const { fileSchema, runApplyDryRunTool, runDeleteFileTool, runEditTool, runFlowTool, runMultieditTool, runMutateTool, runPatchTool, runRenameFileTool, writeFlagSchema } = deps;
  return [
    {
      name: "edit",
      title: "Universal Edit",
      description: "Safer replacement for routine Edit calls: exact, fuzzy, anchor, regex, or line-range edits with git-aware write policy, parse verification, and retry hints. MCP writes by default; pass dryRun:true to preview.",
      category: "edit",
      aliases: ["safe_edit", "base_edit", "edit.replace"],
      bestFor: ["single localized text/code edit", "retryable exact/fuzzy match", "line-range or regex replacement"],
      inputSchema: {
        file: fileSchema,
        find: z.string().optional(),
        findExact: z.string().optional(),
        findFuzzy: z.string().optional(),
        findAnchorAfter: z.string().optional(),
        contains: z.string().optional(),
        findRegex: z.string().optional(),
        flags: z.string().optional(),
        findLines: z.string().optional(),
        replace: z.string().optional(),
        insertBefore: z.string().optional(),
        insertAfter: z.string().optional(),
        delete: z.boolean().optional(),
        replaceAll: z.boolean().optional(),
        expectCount: z.number().int().nonnegative().optional(),
        noFuzzyFallback: z.boolean().optional(),
        ...writeFlagSchema,
      },
      handler: runEditTool,
    },
    {
      name: "multiedit",
      title: "Atomic Multiedit",
      description: "Safer replacement for multiple Edit calls: apply many universal base edits atomically across one or more files with parse verification. MCP writes by default; pass dryRun:true to preview.",
      category: "edit",
      aliases: ["multi_edit", "bulk_edit"],
      bestFor: ["coordinated repeated edits", "same-file sequential edits", "cross-file atomic text changes"],
      inputSchema: {
        edits: z.array(z.record(z.string(), z.unknown())).optional(),
        input: z.string().optional().describe("Raw multiedit JSON string; use when forwarding existing CLI input."),
        ...writeFlagSchema,
      },
      handler: runMultieditTool,
    },
    {
      name: "patch",
      title: "Patch",
      description: "Safer replacement for patch/apply_patch when the change is already a diff: apply unified diff or Codex apply-patch input atomically with verification.",
      category: "edit",
      aliases: ["apply_patch", "unified_diff"],
      bestFor: ["large generated diffs", "file additions/deletions/renames", "Codex apply-patch envelopes"],
      inputSchema: {
        patch: z.string().min(1).describe("Unified diff or apply-patch envelope."),
        ...writeFlagSchema,
      },
      handler: runPatchTool,
    },
    {
      name: "mutate",
      title: "Mutate",
      description: "Single structural mutation facade: pass op, prefixed target, and args; tedit dispatches to the safest file-type backend. MCP writes by default; pass dryRun:true to preview.",
      category: "structure",
      aliases: ["modify", "structure_edit"],
      bestFor: ["one selected structural mutation", "select id then mutate", "agent-facing JSX/TS mutation without choosing backend tools"],
      inputSchema: {
        file: fileSchema,
        op: z.string().min(1).describe("Dotted operation such as prop.set, class.add, text.set, wrap, imports.rename, body.replace, declaration.move, or ast.replace."),
        target: z.union([z.string().min(1), z.record(z.string(), z.unknown())]).optional().describe("Required for JSX/TS/AST ops: jsx:<selector>, id:jsx:<id>, fn:<name>, objectKey:<key>, call:<callee>, etc. Omit for imports.* ops."),
        args: z.record(z.string(), z.unknown()).optional().describe("Operation arguments. Examples: {name,value} for prop.set, {classes} or {className} for class.add/remove, {from,to} for class.replace/imports.rename, {body} for body.replace, {replace} for ast.replace."),
        kind: z.string().optional().describe("Optional validation hint; routing defaults to auto."),
        ...writeFlagSchema,
      },
      handler: runMutateTool,
    },
    {
      name: "apply_dry_run",
      title: "Apply Dry Run",
      description: "Apply a previous successful dry-run by id after verifying the source files have not changed.",
      category: "edit",
      aliases: ["applyDryRun"],
      bestFor: ["applying a reviewed dry-run", "avoiding long argument resubmission", "safe dry-run to write handoff"],
      inputSchema: {
        id: z.string().min(1).describe("Dry-run id from suggestedActions[0].arguments.id."),
      },
      handler: runApplyDryRunTool,
    },
    {
      name: "flow",
      title: "Flow",
      description: "Run a multi-step edit transaction. Pass JSON steps/flow, or pass CLI-style chain with optional file for single-file chain syntax. MCP writes by default; pass dryRun:true to preview.",
      category: "workflow",
      aliases: ["chain", "workflow"],
      bestFor: ["find-then-mutate edits", "CLI-style chain from MCP", "coordinated structural edits"],
      inputSchema: {
        file: fileSchema.optional().describe("Target file for single-file CLI-style chain input."),
        steps: z.array(z.record(z.string(), z.unknown())).optional().describe("Workspace-flow steps. Use for JSON-native MCP calls."),
        flow: z.array(z.record(z.string(), z.unknown())).optional().describe("Alias for steps."),
        chain: z.union([z.string(), z.array(z.string())]).optional().describe("CLI-style chain, either a shell-like string or argv token array. With file, uses `tedit chain <file> ...`; without file, uses workspace-chain syntax."),
        params: z.record(z.string(), z.unknown()).optional().describe("Optional flow parameters."),
        ...writeFlagSchema,
      },
      handler: runFlowTool,
    },
    {
      name: "delete_file",
      title: "Delete File",
      description: "Delete one existing file through tedit's atomic workspace transaction and write policy. Use patch for coordinated delete+edit batches.",
      category: "edit",
      aliases: ["file_delete", "remove_file"],
      bestFor: ["deleting generated files", "small rollback cleanup", "dry-run delete confirmation"],
      inputSchema: {
        file: fileSchema,
        ...writeFlagSchema,
      },
      handler: runDeleteFileTool,
    },
    {
      name: "rename_file",
      title: "Rename File",
      description: "Rename one existing file through tedit's atomic workspace transaction and write policy. Use patch for coordinated rename+edit batches.",
      category: "edit",
      aliases: ["file_rename", "move_file"],
      bestFor: ["renaming generated files", "moving one file", "dry-run rename confirmation"],
      inputSchema: {
        file: fileSchema,
        to: z.string().min(1).describe("Destination file path."),
        ...writeFlagSchema,
      },
      handler: runRenameFileTool,
    }
  ] satisfies readonly TeditMcpTool[];
}
