import { z } from "zod/v4";
import type { TeditMcpTool } from "../../mcp-tools.js";
import type { WorkspaceFlowStep } from "../../workspace-flow.js";

// ponytail: these are legacy single-step wrappers; keep them grouped until handler deps move out of mcp-tools.
export function makeJSX_SINGLE_STEP_TOOLS(deps: any): readonly TeditMcpTool[] {
  const { booleanValue, classNamesInput, elementSchema, exprSchema, fileSchema, importFields, importsSchema, normalizeElementInput, pick, propValue, requiredString, singleStepTool, targetFromInput, selectorSchema, targetOnlySchema, targetSchema, textMatch, textReplacement, textSetValue, valueSchema, writeFlagSchema } = deps;
  return [
  singleStepTool({
    name: "find",
    title: "Find JSX Node",
    action: "find",
    description: "Find structural nodes by selector and return ids for later tedit mutations.",
    readOnly: true,
    inputSchema: { file: fileSchema, selector: selectorSchema, all: z.boolean().optional() },
    buildStep: (input: any) => ({ action: "find", file: requiredString(input.file, "find requires file."), selector: requiredString(input.selector, "find requires selector."), all: booleanValue(input.all) }),
  }),
  singleStepTool({
    name: "inspect",
    title: "Inspect JSX Node",
    action: "inspect",
    description: "Inspect a structural node by selector or id after native Read or find.",
    readOnly: true,
    inputSchema: { file: fileSchema, selector: selectorSchema.optional(), target: targetSchema.optional(), id: targetSchema.optional() },
    buildStep: (input: any) => ({ action: "inspect", file: requiredString(input.file, "inspect requires file."), target: targetFromInput(input, "inspect") }),
  }),
  singleStepTool({
    name: "append",
    title: "Append JSX Element",
    action: "append",
    description: "Append an element inside a selected JSX node.",
    inputSchema: { file: fileSchema, selector: selectorSchema.optional(), target: targetSchema.optional(), id: targetSchema.optional(), element: elementSchema, ...writeFlagSchema },
    buildStep: (input: any) => ({ action: "append", file: requiredString(input.file, "append requires file."), target: targetFromInput(input, "append"), element: normalizeElementInput(input.element, "append requires element.") }),
  }),
  singleStepTool({
    name: "prepend",
    title: "Prepend JSX Element",
    action: "prepend",
    description: "Prepend an element inside a selected JSX node.",
    inputSchema: { file: fileSchema, selector: selectorSchema.optional(), target: targetSchema.optional(), id: targetSchema.optional(), element: elementSchema, ...writeFlagSchema },
    buildStep: (input: any) => ({ action: "prepend", file: requiredString(input.file, "prepend requires file."), target: targetFromInput(input, "prepend"), element: normalizeElementInput(input.element, "prepend requires element.") }),
  }),
  singleStepTool({
    name: "wrap",
    title: "Wrap JSX Node",
    action: "wrap",
    description: "Wrap a selected JSX node.",
    inputSchema: { file: fileSchema, selector: selectorSchema.optional(), target: targetSchema.optional(), id: targetSchema.optional(), with: elementSchema, ...writeFlagSchema },
    buildStep: (input: any) => ({ action: "wrap", file: requiredString(input.file, "wrap requires file."), target: targetFromInput(input, "wrap"), with: normalizeElementInput(input.with, "wrap requires with.") }),
  }),
  singleStepTool({
    name: "unwrap",
    title: "Unwrap JSX Node",
    action: "unwrap",
    description: "Remove a JSX wrapper while keeping children.",
    inputSchema: targetOnlySchema(),
    buildStep: (input: any) => ({ action: "unwrap", file: requiredString(input.file, "unwrap requires file."), target: targetFromInput(input, "unwrap") }),
  }),
  singleStepTool({
    name: "remove",
    title: "Remove JSX Node",
    action: "remove",
    description: "Remove a selected JSX node.",
    inputSchema: targetOnlySchema(),
    buildStep: (input: any) => ({ action: "remove", file: requiredString(input.file, "remove requires file."), target: targetFromInput(input, "remove") }),
  }),
  singleStepTool({
    name: "rename",
    title: "Rename JSX Element",
    action: "rename",
    description: "Rename a selected JSX element tag.",
    inputSchema: { file: fileSchema, selector: selectorSchema.optional(), target: targetSchema.optional(), id: targetSchema.optional(), to: z.string().optional(), name: z.string().optional(), ...writeFlagSchema },
    buildStep: (input: any) => ({ action: "rename", file: requiredString(input.file, "rename requires file."), target: targetFromInput(input, "rename"), name: requiredString(pick(input, "to", "name"), "rename requires to or name.") }),
  }),
  singleStepTool({
    name: "prop_set",
    title: "Set JSX Prop",
    action: "prop.set",
    description: "Set a JSX prop on a selected node.",
    inputSchema: { file: fileSchema, selector: selectorSchema.optional(), target: targetSchema.optional(), id: targetSchema.optional(), name: z.string().min(1), value: valueSchema.optional(), expr: z.string().optional(), ...writeFlagSchema },
    buildStep: (input: any) => ({ action: "prop.set", file: requiredString(input.file, "prop_set requires file."), target: targetFromInput(input, "prop_set"), name: requiredString(input.name, "prop_set requires name."), value: propValue(input) }),
  }),
  singleStepTool({
    name: "prop_remove",
    title: "Remove JSX Prop",
    action: "prop.remove",
    description: "Remove a JSX prop from a selected node.",
    inputSchema: { file: fileSchema, selector: selectorSchema.optional(), target: targetSchema.optional(), id: targetSchema.optional(), name: z.string().min(1), ...writeFlagSchema },
    buildStep: (input: any) => ({ action: "prop.remove", file: requiredString(input.file, "prop_remove requires file."), target: targetFromInput(input, "prop_remove"), name: requiredString(input.name, "prop_remove requires name.") }),
  }),
  singleStepTool({
    name: "class_add",
    title: "Add JSX Class",
    action: "class.add",
    description: "Add one or more static className tokens to a selected JSX node. Accepts classes or className.",
    inputSchema: { file: fileSchema, selector: selectorSchema.optional(), target: targetSchema.optional(), id: targetSchema.optional(), classes: z.union([z.string(), z.array(z.string())]).optional(), className: z.string().optional(), ...writeFlagSchema },
    buildStep: (input: any) => ({ action: "class.add", file: requiredString(input.file, "class_add requires file."), target: targetFromInput(input, "class_add"), classes: classNamesInput(input, "class_add") }),
  }),
  singleStepTool({
    name: "class_remove",
    title: "Remove JSX Class",
    action: "class.remove",
    description: "Remove one or more static className tokens from a selected JSX node. Accepts classes or className.",
    inputSchema: { file: fileSchema, selector: selectorSchema.optional(), target: targetSchema.optional(), id: targetSchema.optional(), classes: z.union([z.string(), z.array(z.string())]).optional(), className: z.string().optional(), ...writeFlagSchema },
    buildStep: (input: any) => ({ action: "class.remove", file: requiredString(input.file, "class_remove requires file."), target: targetFromInput(input, "class_remove"), classes: classNamesInput(input, "class_remove") }),
  }),
  singleStepTool({
    name: "class_replace",
    title: "Replace JSX Class",
    action: "class.replace",
    description: "Replace a static className token on a selected JSX node.",
    inputSchema: { file: fileSchema, selector: selectorSchema.optional(), target: targetSchema.optional(), id: targetSchema.optional(), from: z.string().min(1), to: z.string().min(1), ...writeFlagSchema },
    buildStep: (input: any) => ({ action: "class.replace", file: requiredString(input.file, "class_replace requires file."), target: targetFromInput(input, "class_replace"), from: requiredString(input.from, "class_replace requires from."), to: requiredString(input.to, "class_replace requires to.") }),
  }),
  singleStepTool({
    name: "text_set",
    title: "Set JSX Text",
    action: "text.set",
    description: "Replace all children of a selected node with text or an expression.",
    inputSchema: { file: fileSchema, selector: selectorSchema.optional(), target: targetSchema.optional(), id: targetSchema.optional(), value: z.string().optional(), expr: z.string().optional(), ...writeFlagSchema },
    buildStep: (input: any) => ({ action: "text.set", file: requiredString(input.file, "text_set requires file."), target: targetFromInput(input, "text_set"), ...textSetValue(input) }),
  }),
  singleStepTool({
    name: "text_replace",
    title: "Replace JSX Text",
    action: "text.replace",
    description: "Replace matching direct JSX text/expression children.",
    inputSchema: {
      file: fileSchema,
      selector: selectorSchema.optional(),
      target: targetSchema.optional(),
      id: targetSchema.optional(),
      match: z.unknown().optional(),
      matchText: z.string().optional(),
      matchExpr: z.string().optional(),
      matchAny: z.string().optional(),
      with: z.unknown().optional(),
      withText: z.string().optional(),
      withExpr: z.string().optional(),
      ...writeFlagSchema,
    },
    buildStep: (input: any) => ({ action: "text.replace", file: requiredString(input.file, "text_replace requires file."), target: targetFromInput(input, "text_replace"), match: textMatch(input) as WorkspaceFlowStep["match"], with: textReplacement(input) as WorkspaceFlowStep["with"] }),
  }),
  singleStepTool({
    name: "insert_comment",
    title: "Insert JSX Comment",
    action: "insertComment",
    description: "Insert a JSX comment around or inside a selected node.",
    inputSchema: { file: fileSchema, selector: selectorSchema.optional(), target: targetSchema.optional(), id: targetSchema.optional(), text: z.string().min(1), position: z.string().optional(), ...writeFlagSchema },
    buildStep: (input: any) => ({ action: "insertComment", file: requiredString(input.file, "insert_comment requires file."), target: targetFromInput(input, "insert_comment"), text: requiredString(input.text, "insert_comment requires text."), ...(input.position === undefined ? {} : { position: String(input.position) as WorkspaceFlowStep["position"] }) }),
  }),
  singleStepTool({
    name: "imports_add",
    title: "Add Import",
    action: "imports.add",
    description: "Add or merge an import declaration.",
    inputSchema: importsSchema(),
    buildStep: (input: any) => ({ action: "imports.add", file: requiredString(input.file, "imports_add requires file."), ...importFields(input) }),
  }),
  singleStepTool({
    name: "imports_remove",
    title: "Remove Import",
    action: "imports.remove",
    description: "Remove import specifiers or declarations.",
    inputSchema: importsSchema(),
    buildStep: (input: any) => ({ action: "imports.remove", file: requiredString(input.file, "imports_remove requires file."), ...importFields(input) }),
  }),
  singleStepTool({
    name: "imports_rename",
    title: "Rename Import",
    action: "imports.rename",
    description: "Rename an imported binding.",
    inputSchema: importsSchema({ requireName: true, requireTo: true }),
    buildStep: (input: any) => ({ action: "imports.rename", file: requiredString(input.file, "imports_rename requires file."), ...importFields(input) }),
  }),
  singleStepTool({
    name: "imports_move",
    title: "Move Import",
    action: "imports.move",
    description: "Move an import to a different source module.",
    inputSchema: importsSchema({ requireTo: true }),
    buildStep: (input: any) => ({ action: "imports.move", file: requiredString(input.file, "imports_move requires file."), ...importFields(input) }),
  }),
  singleStepTool({
    name: "expr_replace",
    title: "Replace JSX Expression",
    action: "expr.replace",
    description: "Replace a selected JSX expression container.",
    inputSchema: exprSchema({ code: true }),
    buildStep: (input: any) => ({ action: "expr.replace", file: requiredString(input.file, "expr_replace requires file."), target: targetFromInput(input, "expr_replace"), code: requiredString(input.code, "expr_replace requires code.") }),
  }),
  singleStepTool({
    name: "expr_wrap",
    title: "Wrap JSX Expression",
    action: "expr.wrap",
    description: "Wrap a selected JSX expression with code containing $expr.",
    inputSchema: exprSchema({ code: true }),
    buildStep: (input: any) => ({ action: "expr.wrap", file: requiredString(input.file, "expr_wrap requires file."), target: targetFromInput(input, "expr_wrap"), code: requiredString(input.code, "expr_wrap requires code.") }),
  }),
  singleStepTool({
    name: "expr_unwrap",
    title: "Unwrap JSX Expression",
    action: "expr.unwrap",
    description: "Unwrap a selected JSX expression.",
    inputSchema: exprSchema(),
    buildStep: (input: any) => ({ action: "expr.unwrap", file: requiredString(input.file, "expr_unwrap requires file."), target: targetFromInput(input, "expr_unwrap") }),
  }),
  singleStepTool({
    name: "expr_to_ternary",
    title: "Convert Expression To Ternary",
    action: "expr.toTernary",
    description: "Convert a selected short-circuit expression to a ternary.",
    inputSchema: { ...exprSchema(), alternate: z.string().optional(), value: z.string().optional() },
    buildStep: (input: any) => ({ action: "expr.toTernary", file: requiredString(input.file, "expr_to_ternary requires file."), target: targetFromInput(input, "expr_to_ternary"), ...(pick(input, "alternate", "value") === undefined ? {} : { value: String(pick(input, "alternate", "value")) }) }),
  }),
  singleStepTool({
    name: "expr_to_short_circuit",
    title: "Convert Expression To Short Circuit",
    action: "expr.toShortCircuit",
    description: "Convert a selected ternary expression to a short-circuit expression.",
    inputSchema: exprSchema(),
    buildStep: (input: any) => ({ action: "expr.toShortCircuit", file: requiredString(input.file, "expr_to_short_circuit requires file."), target: targetFromInput(input, "expr_to_short_circuit") }),
  }),
  ] satisfies readonly TeditMcpTool[];
}
