import { z } from "zod/v4";
import type { TeditMcpTool } from "../../mcp-tools.js";

// ponytail: explicit any avoids runtime imports from the source module; tighten when dependency typing matters.
export function makeJSX_TOOLS(deps: any) {
  const { elementSchema, fileSchema, importsSchema, runExtractComponentTool, runExtractTool, runImportsTool, runJsxAttrTool, runJsxContentTool, runJsxNodeTool, runJsxSelectTool, selectorSchema, targetSchema, valueSchema, writeFlagSchema } = deps;
  return [
    {
      name: "jsx_select",
      title: "JSX Select",
      description: "Read-only JSX selector facade. action=find returns matching node ids/previews; action=inspect returns one node's details. Both are safe discovery operations.",
      category: "jsx",
      aliases: ["find", "inspect"],
      bestFor: ["selector discovery", "inspecting JSX nodes before mutation", "getting stable target ids"],
      inputSchema: {
        action: z.enum(["find", "inspect"]).describe("Required. find lists matching nodes; inspect returns details for one selector/id."),
        file: fileSchema,
        selector: selectorSchema.optional().describe("Required for action=find; accepted for action=inspect."),
        target: targetSchema.optional().describe("Selector or returned id for action=inspect."),
        id: targetSchema.optional().describe("Returned node id for action=inspect."),
        all: z.boolean().optional().describe("For action=find, return all matches when supported."),
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
      handler: runJsxSelectTool,
    },
    {
      name: "jsx_node",
      title: "JSX Node",
      description: "JSX node mutation facade. Required action. append/prepend require element; wrap requires with/wrapper; rename requires to/name; insert_comment requires text.",
      category: "jsx",
      aliases: ["append", "prepend", "wrap", "unwrap", "remove", "rename", "insert_comment"],
      bestFor: ["structural JSX node edits", "wrapping/removing/renaming JSX", "comment insertion"],
      inputSchema: {
        action: z.enum(["append", "prepend", "wrap", "unwrap", "remove", "rename", "insert_comment"]).describe("Required node operation."),
        file: fileSchema,
        selector: selectorSchema.optional(),
        target: targetSchema.optional(),
        id: targetSchema.optional(),
        element: elementSchema.optional().describe("Required for action=append or action=prepend."),
        with: elementSchema.optional().describe("Required for action=wrap; wrapper shorthand/object."),
        wrapper: elementSchema.optional().describe("Alias for with when action=wrap."),
        to: z.string().optional().describe("Required for action=rename unless name is supplied."),
        name: z.string().optional().describe("Alias for to when action=rename."),
        text: z.string().optional().describe("Required for action=insert_comment."),
        position: z.string().optional().describe("Optional insert_comment position: inside-start, inside-end, before, or after."),
        ...writeFlagSchema,
      },
      handler: runJsxNodeTool,
    },
    {
      name: "jsx_attr",
      title: "JSX Attr",
      description: "JSX prop/class mutation facade. Required action. prop_set/remove use name/value/expr; class_add/remove use classes; class_replace uses from/to.",
      category: "jsx",
      aliases: ["prop_set", "prop_remove", "class_add", "class_remove", "class_replace"],
      bestFor: ["JSX prop edits", "static className token edits", "attribute-level changes"],
      inputSchema: {
        action: z.enum(["prop_set", "prop_remove", "class_add", "class_remove", "class_replace"]).describe("Required attr/class operation."),
        file: fileSchema,
        selector: selectorSchema.optional(),
        target: targetSchema.optional(),
        id: targetSchema.optional(),
        name: z.string().optional().describe("Required for prop_set and prop_remove."),
        value: valueSchema.optional().describe("Optional prop_set value; defaults to true when expr is omitted."),
        expr: z.string().optional().describe("Optional prop_set expression value."),
        classes: z.union([z.string(), z.array(z.string())]).optional().describe("Required for class_add and class_remove."),
        from: z.string().optional().describe("Required for class_replace."),
        to: z.string().optional().describe("Required for class_replace."),
        ...writeFlagSchema,
      },
      handler: runJsxAttrTool,
    },
    {
      name: "jsx_content",
      title: "JSX Content",
      description: "JSX text/expression mutation facade. Required action. text_set needs value or expr; text_replace needs match/with fields; expr_replace/wrap need code.",
      category: "jsx",
      aliases: ["text_set", "text_replace", "expr_replace", "expr_wrap", "expr_unwrap", "expr_to_ternary", "expr_to_short_circuit"],
      bestFor: ["text child replacement", "expression container edits", "ternary/short-circuit conversions"],
      inputSchema: {
        action: z.enum(["text_set", "text_replace", "expr_replace", "expr_wrap", "expr_unwrap", "expr_to_ternary", "expr_to_short_circuit"]).describe("Required content/expression operation."),
        file: fileSchema,
        selector: selectorSchema.optional(),
        target: targetSchema.optional(),
        id: targetSchema.optional(),
        value: z.string().optional().describe("text_set value or expr_to_ternary alternate alias."),
        expr: z.string().optional().describe("text_set expression value."),
        match: z.unknown().optional().describe("text_replace match spec."),
        matchText: z.string().optional(),
        matchExpr: z.string().optional(),
        matchAny: z.string().optional(),
        with: z.unknown().optional().describe("text_replace replacement spec."),
        withText: z.string().optional(),
        withExpr: z.string().optional(),
        code: z.string().optional().describe("Required for expr_replace and expr_wrap."),
        alternate: z.string().optional().describe("Optional expr_to_ternary alternate."),
        ...writeFlagSchema,
      },
      handler: runJsxContentTool,
    },
    {
      name: "imports",
      title: "Imports",
      description: "Import declaration facade. Required action: add, remove, rename, or move. rename requires name and to; move requires to.",
      category: "jsx",
      aliases: ["imports_add", "imports_remove", "imports_rename", "imports_move"],
      bestFor: ["adding imports", "removing imports", "renaming or moving import specifiers"],
      inputSchema: {
        action: z.enum(["add", "remove", "rename", "move"]).describe("Required import operation."),
        ...importsSchema(),
      },
      handler: runImportsTool,
    },
    {
      name: "extract_component",
      title: "Extract Component",
      description: "JSX component extraction facade. mode=plan writes a reviewable plan and requires planOut; mode=direct runs the extraction through workspace-flow dry-run/write policy.",
      category: "refactor",
      aliases: ["extract", "extract_plan", "component_extract"],
      bestFor: ["component extraction", "reviewable extract plans", "small direct extract dry-runs"],
      inputSchema: {
        mode: z.enum(["plan", "direct"]).describe("Required. plan writes a reviewable plan; direct runs extraction with dry-run/write policy."),
        from: fileSchema.describe("Source JSX/TSX file containing the subtree to extract."),
        selector: selectorSchema.describe("CSS-like selector for the JSX subtree to extract."),
        to: z.string().min(1).describe("Destination component file."),
        name: z.string().min(1).describe("New component name."),
        planOut: z.string().optional().describe("Required when mode=plan."),
        export: z.enum(["named", "default"]).optional(),
        exportKind: z.enum(["named", "default"]).optional(),
        slots: z.unknown().optional(),
        slot: z.unknown().optional(),
        depth: z.number().int().optional(),
        autoSlot: z.boolean().optional(),
        helpers: z.string().optional(),
        helpersPolicy: z.string().optional(),
        helper: z.unknown().optional(),
        helperOverrides: z.unknown().optional(),
        overwrite: z.boolean().optional(),
        typecheck: z.boolean().optional(),
        maxProps: z.number().int().optional(),
        acceptLargeProps: z.boolean().optional(),
        ...writeFlagSchema,
      },
      handler: runExtractComponentTool,
    },
    {
      name: "extract",
      title: "Extract JSX Component",
      description: "Directly extract a JSX subtree into a new component file. Required: from, selector, to, name. Dry-run by default; pass write:true to persist. For large/risky extracts use extract_plan then apply_plan; for extract plus follow-up edits use chain_workspace.",
      category: "refactor",
      exposure: "advanced",
      aliases: ["extract_component", "component_extract"],
      bestFor: ["small confident JSX component extraction", "single-step component extraction", "dry-run extraction preview"],
      inputSchema: {
        from: fileSchema.describe("Source JSX/TSX file containing the component subtree to extract."),
        selector: selectorSchema.describe("CSS-like selector for the JSX subtree to extract, e.g. Card, DialogFooter > Button, main > section:has(> h2)."),
        to: z.string().min(1).describe("Destination component file to create."),
        name: z.string().min(1).describe("New component name to generate and import at the call site."),
        export: z.enum(["named", "default"]).optional().describe("Generated component export style. Defaults to named."),
        exportKind: z.enum(["named", "default"]).optional().describe("Alias for export. Defaults to named."),
        slots: z.unknown().optional().describe("Slot selectors such as ['CardBody.children'] or ['CardHeader.children=header'] to leave selected children at the call site."),
        slot: z.unknown().optional().describe("Single slot or repeated slot input; same semantics as slots."),
        depth: z.number().int().optional().describe("Ask tedit to suggest slot boundaries at this depth. Requires autoSlot to accept suggestions automatically."),
        autoSlot: z.boolean().optional().describe("Accept depth-generated slot suggestions intentionally."),
        helpers: z.string().optional().describe("Default helper policy: ask, move, share, or as-prop."),
        helpersPolicy: z.string().optional().describe("Alias for helpers: ask, move, share, or as-prop."),
        helper: z.unknown().optional().describe("Per-helper override such as helperName=as-prop, helperName=move, helperName=share, or helperName=leave."),
        helperOverrides: z.unknown().optional().describe("Per-helper overrides; same semantics as helper."),
        overwrite: z.boolean().optional().describe("Allow overwriting the destination file if it already exists."),
        typecheck: z.boolean().optional().describe("Use the local TypeScript checker for stronger prop type inference when available."),
        maxProps: z.number().int().optional().describe("Run-specific maximum generated prop count before tedit refuses the extraction."),
        acceptLargeProps: z.boolean().optional().describe("Explicitly accept an extraction whose generated prop count exceeds the configured threshold."),
        ...writeFlagSchema,
      },
      handler: runExtractTool,
    }
  ] satisfies readonly TeditMcpTool[];
}
